import nodemailer from 'nodemailer';

// Create transporter
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST,
  port: process.env.EMAIL_PORT,
  secure: false, // true for 465, false for others
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASSWORD,
  },
});

// Base email sender
export const sendEmail = async ({ to, subject, text, html, attachments }) => {
  try {
    const mailOptions = {
      from: `studyguardian <${process.env.EMAIL_USER}>`,
      to,
      subject,
      text,
      html,
      attachments,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('✅ Email sent:', info.messageId);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('❌ Email send error:', error);
    return { success: false, error: error.message };
  }
};

// Send study report email
export const sendStudyReport = async (teacherEmail, studentName, reportData) => {
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #2563eb;">Study Report from ${studentName}</h2>
      <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <h3>Session Summary</h3>
        <ul style="list-style: none; padding: 0;">
          <li><strong>Duration:</strong> ${reportData.duration} minutes</li>
          <li><strong>Pages Visited:</strong> ${reportData.pages_visited}</li>
          <li><strong>Highlights:</strong> ${reportData.total_highlights}</li>
          <li><strong>Presence:</strong> ${reportData.presence_percentage}%</li>
        </ul>
      </div>
      ${reportData.ai_summary ? `
        <div style="background-color: #eff6ff; padding: 20px; border-radius: 8px; margin: 20px 0;">
          <h3>AI Insights</h3>
          <p>${reportData.ai_summary}</p>
        </div>
      ` : ''}
      <p style="color: #6b7280; font-size: 14px;">
        This report was generated by studyguardian.
      </p>
    </div>
  `;

  return await sendEmail({
    to: teacherEmail,
    subject: `Study Report from ${studentName}`,
    html,
  });
};

// Send notification email
export const sendNotification = async (studentEmail, studentName, message) => {
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #2563eb;">New Notification</h2>
      <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <p style="font-size: 16px;">${message}</p>
      </div>
      <p style="color: #6b7280; font-size: 14px;">
        Login to studyguardian to view details.
      </p>
    </div>
  `;

  return await sendEmail({
    to: studentEmail,
    subject: 'New studyguardian Notification',
    html,
  });
};

// Send room invitation email
export const sendRoomInvitation = async (studentEmail, roomTitle, roomCode, teacherName) => {
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #2563eb;">You've been invited to a Study Room!</h2>
      <div style="background-color: #f3f4f6; padding: 20px; border-radius: 8px; margin: 20px 0;">
        <p><strong>Teacher:</strong> ${teacherName}</p>
        <p><strong>Room:</strong> ${roomTitle}</p>
        <p><strong>Room Code:</strong> 
          <span style="font-size: 24px; color: #2563eb; font-weight: bold;">${roomCode}</span>
        </p>
      </div>
      <p>Login to studyguardian and use the room code to join.</p>
    </div>
  `;

  return await sendEmail({
    to: studentEmail,
    subject: `Invitation to Study Room: ${roomTitle}`,
    html,
  });
};

// ⭐️ NEW: Send session report email (used by interactions.js)
export const sendReportEmail = async ({ to, subject, html, studentName, sessionDate }) => {
  const wrappedHtml = `
    <div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto;">
      <div style="background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin-bottom: 20px;">
        <h1 style="color: #2563eb; margin: 0;">📊 Study Session Report</h1>
        <p style="color: #6b7280; margin: 10px 0 0 0;">
          From: <strong>${studentName}</strong> | Date: <strong>${sessionDate}</strong>
        </p>
      </div>
      ${html}
      <div style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb;">
        <p style="color: #9ca3af; font-size: 14px;">
          This report was automatically generated by studyguardian Analytics System
        </p>
      </div>
    </div>
  `;

  return await sendEmail({
    to,
    subject,
    html: wrappedHtml,
  });
};

// ⭐️ ADD DEFAULT EXPORT for compatibility
const emailService = {
  sendEmail,
  sendStudyReport,
  sendNotification,
  sendRoomInvitation,
  sendReportEmail,
};

export default emailService;